---
- name: Play 1 - Fetch file from host
  hosts: fd*.shadowman.dev
  gather_facts: false
  tasks:

  - name: Sync with Gitrepo
    ansible.builtin.git:
      repo: 'https://github.com/mogreen1/backup.git'
      dest: /tmp/backup
      version: master
      #force: true
      #clone: false
      accept_newhostkey: true
      key_file: /certs/id_ed25519
    run_once: true
    delegate_to: localhost
    
  - name: Fetch file to EE
    ansible.builtin.fetch:
      src: "/etc/{{ item }}"
      dest: "/tmp/backup/{{ inventory_hostname }}/{{ item }}.txt"
      flat: true
    become: true
    loop:
      - sudoers
      - passwd
      - group

  - name: Update git repo with backup
    ansible.builtin.shell: git add -A && git commit -m "Synching new backup to repo" && git push
    args:
      chdir: /tmp/backup
    run_once: true
    delegate_to: localhost
