---
- name: Add new address object to PAN firewall
  hosts: localhost
  connection: local
  vars:
    pre_object_name: []
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"

  tasks:

    - name:  Gather all objects
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        state: gathered
        gathered_filter: '*'
      register: all_pan_objects

    - name: Get pre-existing object name
      set_fact: 
        pre_object_name: "{{ pre_object_name + [ item.name ] }}"
      loop: "{{ all_pan_objects.gathered }}"
      when: item.value == object_ip

    - name: Fail if IP already exists
      block: 
        - name: Set stats to pass through workflow template
          set_stats: 
            data:
              work_notes: "ERROR!!! The entry [  {{ object_ip }}  ] already exists in the following address object(s): [  {{ pre_object_name.0 }}  ] "
              close_notes: "ERROR!!! The entry [  {{ object_ip }}  ] already exists in the following address object(s): [  {{ pre_object_name.0 }}  ] "
              close_code: "unsuccessful"
            per_host: no
            aggregate: no

        - name: Display error if object already exists
          fail:
            msg: "ERROR!!! The entry [  {{ object_ip }}  ] already exists in the following address object(s): [  {{ pre_object_name.0 }}  ] "
          
      when: pre_object_name | length > 0
      
    - name: Create address object
      paloaltonetworks.panos.panos_address_object:
        provider: 
          ip_address: "{{ palo_ip_address }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: '{{ object_name }}'
        address_type: 'ip-netmask'
        value: '{{ object_ip }}'
      when: pre_object_name | length == 0

    - name: Create or modify object group
      paloaltonetworks.panos.panos_address_group:
        provider: 
          ip_address: "{{ palo_ip_address }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: 'BadGuys'
        static_value: "{{ object_name }}"
        state: 'merged'
      when: pre_object_name | length == 0
