---
- name: Play 1 - Fetch file from host
  hosts: fd1.shadowman.dev
  gather_facts: false
  tasks:

  - name: Fetch file to EE
    ansible.builtin.fetch:
      src: "/etc/{{ item }}"
      dest: "/tmp/{{ item }}.txt"
      flat: true
    become: true
    run_once: true
    register: myfile
    loop:
      - sudoers
      - passwd
      - group
  
- name: Play 2 - Modiying SNOW Record 
  hosts: localhost
  gather_facts: true
  connection: local
  tasks:

  - name: Update SNOW CMDB
    servicenow.itsm.configuration_item:
      state: "{{ status }}"
      #OS_Version: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
      name: "{{ recordname }}"
      sys_class_name: cmdb_ci_server
      sys_id: "{{ system_id }}"
      attachments:
        - path: "/tmp/{{ item }}.txt"
      other:
        model_number: BL465C G7
        cost: " {{ ansible_facts['distribution_version'] }} "
    delegate_to: localhost
    loop:
      - sudoers
      - passwd
      - group
