---
- name: Play 1 - Fetch file from host
  hosts: fd1.shadowman.dev
  gather_facts: false
  tasks:

  - name: Fetch file to EE
    ansible.builtin.fetch:
      src: "/etc/sudoers"
      dest: "/tmp/"
      flat: true
    become: true
    run_once: true
    register: myfile
    
  - name: 
    debug:
      var: myfile

