---
- name: Play 1 - Test Grabbing SNOW Data
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

  - name: Retrieve all configuration items
    servicenow.itsm.configuration_item_info:
      sys_id: "{{ system_id }}"
    register: result

  - name: Print Results
    debug:
      var: result
