---
- name: Play 1 - Modiying SNOW Record 
  hosts: fd1.shadowman.dev
  gather_facts: true
  tasks:

  - name: Fetch file to EE
    ansible.builtin.fetch:
      src: "/tmp/tempfile.txt"
      dest: "/tmp/"
      flat: true
    become: false
    run_once: true
    register: myfile

  - name: Print File
    debug:
      var: myfile
