---
- name: Play 1 - Fetch file from host
  hosts: fd*.shadowman.dev
  gather_facts: true
     
  tasks:

  - name: Fetch file to EE
    ansible.builtin.fetch:
      src: "/etc/{{ item }}"
      dest: "/tmp/{{ inventory_hostname }}/{{ item }}.txt"
      flat: true
    become: true
    #run_once: true
    register: myfile
    #delegate_to: "{{ inventory_hostname }}"
    loop:
      - sudoers
      - passwd
      - group
      
  - name: 
    ansible.builtin.command: sudo -i grep -vE '#|^$|Defaults' /etc/sudoers
    register: output

  - name: Update SNOW CMDB
    servicenow.itsm.configuration_item:
      state: "{{ status }}"
      name: "{{ inventory_hostname }}"
      sys_class_name: cmdb_ci_server
      #sys_id: "{{ system_id }}"
      attachments:
        - path: "/tmp/{{ inventory_hostname }}/{{ item }}.txt"
      other:
        os_version: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
        cpu_count: "{{ ansible_facts['processor_nproc'] }}"
        default_gateway: "{{ ansible_facts['default_ipv4']['gateway'] }}"
        ip_address: "{{ ansible_facts['default_ipv4']['address'] }}"
        host_name: "{{ ansible_facts['fqdn'] }}"
        u_glide_list_2: "{{ output['stdout_lines'] }}"
        os_service_pack: "{{ ansible_facts['kernel'] }}"
         
    delegate_to: localhost
    loop:
      - sudoers
      - passwd
      - group
